language: go
go:
  - 1.4
  - 1.5
  - tip

before_install:
  - sudo apt-get remove -y gearman-job-server
  - sudo apt-get install -y gearman-job-server
install:
  - go get -v https://github.com/mikespook/gearman-go/client
  - go get -v https://github.com/mikespook/gearman-go/worker
before_script:
  - tree /home/travis/.gimme/versions/go1.5.linux.amd64/pkg/tool/
